apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-iac-coupled-dev
resources:
- ../../../kustomize/base
images:
# Tag updated by deploy-app's kustomize-set-image step.
- name: ghcr.io/akuity/sedemo-monorepo-rollouts-app
  newTag: 48-red
